### ISSUE TITLE
What versions does this tool support?

### ISSUE THREAD

**Issue by ghost** [swisskyrepo/DamnWebScanner#1]
hi, Does this tool only support python3? The following error message appears
 when i run it with Python 2.7.10. 
```
(DamnWebScanEnv) ➜  Server git:(master) ✗ ./launch.sh 
[2017-06-19 15:19:07 +0800] [13482] [INFO] Starting gunicorn 19.7.1
[2017-06-19 15:19:07 +0800] [13482] [INFO] Listening at: http://127.0.0.1:8000 (13482)
[2017-06-19 15:19:07 +0800] [13482] [INFO] Using worker: sync
[2017-06-19 15:19:07 +0800] [13485] [INFO] Booting worker with pid: 13485
[2017-06-19 15:19:07 +0800] [13485] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/Server/server.py", line 4, in <module>
    from ghost import Ghost
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/ghost/__init__.py", line 1, in <module>
    from .ghost import (
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/ghost/ghost.py", line 9, in <module>
    from http.cookiejar import Cookie, LWPCookieJar
ImportError: No module named http.cookiejar
[2017-06-19 15:19:07 +0800] [13485] [INFO] Worker exiting (pid: 13485)
[2017-06-19 15:19:07 +0800] [13486] [INFO] Booting worker with pid: 13486
[2017-06-19 15:19:07 +0800] [13486] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/Server/server.py", line 4, in <module>
    from ghost import Ghost
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/ghost/__init__.py", line 1, in <module>
    from .ghost import (
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/ghost/ghost.py", line 9, in <module>
    from http.cookiejar import Cookie, LWPCookieJar
ImportError: No module named http.cookiejar
[2017-06-19 15:19:07 +0800] [13486] [INFO] Worker exiting (pid: 13486)
Traceback (most recent call last):
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/Users/komi/Pentest/Tools/DamnWebScanner/DamnWebScanEnv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
(DamnWebScanEnv) ➜  Server git:(master) ✗ 

```

**Comment by swisskyrepo** [comment]
It's now in Python 3. A docker image is provided to avoid any dependencies' problems  https://github.com/swisskyrepo/DamnWebScanner/commit/153c7d86b182d81ad62924b1b7ab632fad675af8
